name: 云·爬虫

on:
  workflow_dispatch:
    inputs:
      Start:
        description: '起始id'
        required: true
        default: '1'
      End:
        description: '截止id'
        required: true
        default: '100'
      Threads:
        description: '线程数(默认4)'
        required: false
        default: '4'
      Time:
        description: '运行时间'
        required: true
        default: '100'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: 安装Python3环境
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: 安装JDK8环境
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: 安装requirements.txt
        run: pip install -r requirements.txt

      - name: 开跑
        run: python ./LASEr.py ${{ github.event.inputs.Start }} ${{ github.event.inputs.End }} ${{ github.event.inputs.Threads }} ${{ github.event.inputs.Time }}

      - name: 移动result.txt
        run: |
          move ./result.txt ./result/result.txt

      - name: 上传Artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result/
